apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - image: eclipse-mosquitto:latest
          name: mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: mosquitto-persistent-storage
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
        - name: health-check-sidecar
          image: python:3.9-slim
          command: [ "python3", "-m", "http.server", "80" ]
          ports:
            - containerPort: 80
      volumes:
        - name: {{.Values.name}}-persistent-storage
          persistentVolumeClaim:
            claimName: mq-pv-claim
        - name: {{.Values.name}}-config
          configMap:
            name: {{.Values.name}}-config

