apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Cette annotation permet de créer un LoadBalancer externe sur AWS
spec:
  ports:
{{/*    - port: 1883*/}}
{{/*      targetPort: 1883*/}}
{{/*      name: mqtt*/}}
    - port: 8080
      targetPort: 8080
      name: wss
{{/*    - port: 80*/}}
{{/*      targetPort: 80*/}}
{{/*      name: http*/}}
  selector:
    app: {{ .Values.name }}
  type: NodePort
